// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg5rJqNkFQ0emZhXLomXZ4B4DIPxsmC6w',
    appId: '1:399059097501:web:03150860c059915568c174',
    messagingSenderId: '399059097501',
    projectId: 'bookshare-1b137',
    authDomain: 'bookshare-1b137.firebaseapp.com',
    storageBucket: 'bookshare-1b137.appspot.com',
    measurementId: 'G-5B0MWGVN24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI70I1_xK0LF8huJZPCYRnbPtA4Mrzzo0',
    appId: '1:399059097501:android:c5350a60c322562e68c174',
    messagingSenderId: '399059097501',
    projectId: 'bookshare-1b137',
    storageBucket: 'bookshare-1b137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3WTHPDp7HohE5Iqq7tX8uPYd6hHRJOhA',
    appId: '1:399059097501:ios:9fb9c12e4cfb245668c174',
    messagingSenderId: '399059097501',
    projectId: 'bookshare-1b137',
    storageBucket: 'bookshare-1b137.appspot.com',
    iosClientId: '399059097501-9pi8olfujb429f1enr0k2sefa70619pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookshare',
  );
}
